---
- name: restart apache
  service: name=apache2 state=restarted
  become: yes

- name: restart mysql
  service: name=mysql state=restarted
  become: yes

- name: restart vsftpd
  service: name=vsftpd state=restarted
  become: yes

